//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment2_EnterpriseComputing.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Instructor
    {
        public int InstructorID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Service_Status { get; set; }
        public string Specialization { get; set; }
        public int ProgramID { get; set; }
    
        public virtual Program Program { get; set; }
    }
}
